### PR TITLE
Stylesheet fix

### PR DESCRIPTION
**Pull request by mathieupost**

### CODE REVIEW

**Comment by Delfil** [comment]
It looks great, but the arrows give no extra or valuable information, while it asks our attention. We could probably better remove it?

**Comment by Delfil** [comment]
Is this a rebase or a merge?

**Comment by mathieupost** [comment]
I thought it could be usefull, but I can remove them.
I rebased, but with a lot of conflicts that I had to merge, so it's kinda both.

**Comment by borismattijssen** [comment]
Looking good! I like the arrows for now (could be useful for debugging i guess), we could leave them out in the final version.

**Pull request merged**
