### PR TITLE
Sidebar

### PR DESCRIPTION
**Pull request by kwendel**
UI now has a sidebar which can be hide/show with the spacebar, and it has a new theme!

wow 
much good look

Take a look at it if you have the time so we can merge it at the beginning of our next sprint

### CODE REVIEW

**Comment by TomBrouws** [comment]
untitled
The views only appear in the upperleft corner of the screen for me. :(

**Comment by kwendel** [comment]
Should work on mac now, please try again and let me know :)

**Comment by TomBrouws** [comment]
Looks good now! Spacebar is not working for me though.

**Comment by kwendel** [comment]
stupid mac's :stuck_out_tongue: 
works on my machine

**Comment by Delfil** [comment]
tudelft.ti2806.pl3.ScreenSize.java#calculate( : double, : int) : int
is not a describing name.
Missing java doc on
tudelft.ti2806.pl3.Application.java#toggleSideBar() : void

**Comment by Delfil** [comment]
"Constructor." as javadoc isn't sufficient.

**Comment by Delfil** [comment]
Code is fine. Still the "Constructor" javadocs.

**Comment by kwendel** [comment]
wow so good

**Pull request merged**
