### PR TITLE
Fix/sidebarnotloaded

### PR DESCRIPTION
**Pull request by kwendel**
User is notified when the phylo tree is not loaded but spacebar is pressed

### CODE REVIEW

**Comment by TomBrouws** [comment]
Works and looks good!

**Comment by borismattijssen** [comment]
Why you do this?
We already have a message saying the tree is not loaded :')

**Comment by mathieupost** [comment]
Wat boriez zegt ja

**Comment by kwendel** [comment]
why you make that? it wasn't on your sprint.
But much agree that your solution is better

**Comment by mathieupost** [comment]
So just close this PR then.

**Pull request closed without merging**
