### PR TITLE
Node positioning

### PR DESCRIPTION
**Pull request by Delfil**
Working positioning & zooming of nodes.

### CODE REVIEW

**Comment by borismattijssen** [comment]
Still I am not able to select both the node and edge files. Once I've selected the .node.graph file using the file browser, the application stalls. 
Also there are two classes containing the public static main method. This should only be in the tudelft.ti2806.pl3.Main class.

**Comment by Delfil** [comment]
Are you not getting a second file selection window to select the .edge.graph file?
About the two main methods, I'm working on it.

**Comment by borismattijssen** [comment]
Yep exactly that

**Comment by kwendel** [comment]
looks good!

**Comment by TomBrouws** [comment]
Getting the same bug as Boris mentioned for the demo class, otherwise the codebase looks good!

**Comment by kwendel** [comment]
Why are there 2 cases of GraphController and GraphViewer? Viewer should be extending JPanel since we are using the swing UI in our application and the Controller must implement the interface Controller. 
Now only the demo works, main still uses the old classes which is weird in my opinion

**Comment by borismattijssen** [comment]
Yo is goed

**Comment by kwendel** [comment]
looks good!

**Comment by mathieupost** [comment]
Mooie ding

**Pull request merged**
