### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by borismattijssen**
Lekker ui!
Beetje basis opzetje voor jullie hutten.
Bestaat uit twee MVC packages voor de graph en de zoom bar. En een lege data repository.

### CODE REVIEW

**Comment by Delfil** [comment]
The main method in the class Main thows an IllegalComponentStateException.
Also this branch is 22 commits behind master. Maybe we should merge the master into this branch first, for a seamless pull to the master?

**Comment by borismattijssen** [comment]
Fair enough. This version has the master merged in it. I don't see where the main throws an IllegalComponentStateException?

**Comment by Delfil** [comment]
Exception in thread "main" java.awt.IllegalComponentStateException: contentPane cannot be set to null.
	at javax.swing.JRootPane.setContentPane(JRootPane.java:621)
	at javax.swing.JDialog.setContentPane(JDialog.java:1047)
	at tudelft.ti2806.pl3.Main.<init>(Main.java:30)
	at tudelft.ti2806.pl3.Main.main(Main.java:67)

Try to run FindBugs on Main.java
Everything else seems fine.

**Comment by borismattijssen** [comment]
Ok, rewritten my code to just use Java to init the GUI. So no more findbugs errors pop up there. 
@Delfil my findbugs found some bugs in files that were already pushed to the master. Can u fix them? 
main_java_-__app__-_programminglife3_-____dev_tu_contextproject_programminglife3_

**Comment by Delfil** [comment]
First two problems fixed. Only the first one is a real error, the others are warnings, which my Findbugs can't find somehow.
Fixing the vulnerability of our byte and Genome array might be expensive in computation time, maybe we should put a warning in the java docs instead.

**Comment by mathieupost** [comment]
Hoi

**Comment by kwendel** [comment]
Fixed some missing javadoc, code looks fine!
Still missing a file selector for the data which is hard coded right now. 
Will be adding one

**Comment by TomBrouws** [comment]
This looks good now!

**Comment by TomBrouws** [comment]
Fixed some last Findbugs issues

**Comment by Delfil** [comment]
Looks fine, can be pulled to master.

**Comment by Delfil** [comment]
Looks fine, can be pulled to master.

**Comment by borismattijssen** [comment]
All gucci

**Comment by TomBrouws** [comment]
No changes, but nice :+1:

**Pull request merged**
