### PR TITLE
Feature/lastopenedfiles

### PR DESCRIPTION
**Pull request by kwendel**
Apps tracks which files where opened. When shutting down this data is saved in a .txt file

### CODE REVIEW

**Comment by TomBrouws** [comment]
Works on Mac! Will check code quality later

**Comment by TomBrouws** [comment]
Code looks good as well

**Comment by Delfil** [comment]
Only works after restarting program.

**Comment by mathieupost** [comment]
It works! Hidden! hfs! hidden file system!

**Comment by TomBrouws** [comment]
This works correctly now!

**Pull request merged**
