### PR TITLE
Fix/empty edges in graph

### PR DESCRIPTION
**Pull request by Delfil**
Empty edges where not removed on every layer.

### CODE REVIEW

**Comment by mathieupost** [comment]
image

This shouldn't happen I guess.

**Comment by Delfil** [comment]
Nothing changed there. I'm working on fixing this in a different branch, optimiseXSpace. But this problem already exists on the master. It could be invisible because the fixed bug caused a better distrubuted view.

**Comment by mathieupost** [comment]
Well everything changed here. Normaly it looks like this:
image

**Comment by Delfil** [comment]
Bug found, causing this problem in the first place. Fixed in other branch, invest/optimiseXSpace

**Pull request closed without merging**
