### PR TITLE
Much icon. Wow.

### PR DESCRIPTION
**Pull request by mathieupost**
Must do maven install and run the jar file. Doesn't work when running from your favorite IDE.

### CODE REVIEW

**Comment by Delfil** [comment]
It works!

**Comment by TomBrouws** [comment]
Doesn't work for me :( Where am I supposed to see the icon?

**Comment by Delfil** [comment]
You are supposed to see this
succes

**Comment by TomBrouws** [comment]
Nope not seeing that
screen shot 2015-06-22 at 16 09 59

**Comment by TomBrouws** [comment]
On Mac no icon is displayed on the app itself so that's not a problem but the dock icon is

**Comment by mathieupost** [comment]
Did you run the jar file or straight from intellij?

**Comment by TomBrouws** [comment]
Jar

**Comment by kwendel** [comment]
looks cool!

**Comment by Delfil** [comment]
Requires manual packaging to work for OS X, but works for every other tested OS. (Ubuntu & Windows)

**Pull request merged**
