### PR TITLE
One file select

### PR DESCRIPTION
**Pull request by TomBrouws**
Implement folder selection for data files. This needed a slight change in the file selection process, as FileDialog only allows directory picking on Mac. New menu bar buttons are added to access the new functionality.

### CODE REVIEW

**Comment by borismattijssen** [comment]
Cool

**Comment by kwendel** [comment]
Looks good!

**Comment by TomBrouws** [comment]
Get your own branch!

**Comment by mathieupost** [comment]
:open_mouth:

**Pull request merged**
